### PR TITLE
Upgrade to react 17 and remove package dependencies of < 17

### PR DESCRIPTION
**Pull request by kyorkston**
* Removes package dependencies of React < 17
* Upgrades React and types packages to 17
* Addes react-testing-library for testing

- [x] Unit tests run
- [x] Build scripts run

### CODE REVIEW

**Comment by liamjdouglas** [comment]
@troch @thisRaptori do either of you still have access to npm for this for publishing updates? If so are you able to grant access/transfer ownership please

**Comment by thisRaptori** [comment]
@liamjdouglas yep! Could you confirm your username on npm? Also make sure you've got 2FA enabled!

**Comment by kyorkston** [comment]
Could you add me @thisRaptori ? It's kyorkston on npm

**Comment by thisRaptori** [comment]
Done! @kyorkston

**Review by liamjdouglas — APPROVED** [review]

**Pull request merged**
