### PR TITLE
V2 Documentation

### PR DESCRIPTION
**Pull request by troch**
Documentation branch (only to be merged post v2 release). Getting the ball rolling...

### CODE REVIEW

**Comment by troch** [comment]
@jtmcgrath my initial thoughts are:
- should we focus now on reactive programming over side-effects?
- should the usage section reflect the usage cases, I'm thinking of the following order:
  - You can observe React, Redux, anything
  - You can trigger side-effects, on what you observe
  - But, we have special effects `toProps` and `asProps`: they allow you to manipulate / transform props, do sideways data loading (even replacing `connect`)
  - You can observe events, combined with prop injection, Refract can act as a state container
  - Ultimate level: don't stop at injecting props, render as an effect

**Comment by jtmcgrath** [comment]
Yep that sounds good to me! Imagine side-effects would still be prominent simply because that's a major advantage of using reactive programming, but definitely worth framing it differently.

**Comment by troch** [comment]
I think side-effects are the first obvious and easiest use of Refract for an existing application.

**Comment by troch** [comment]
I've created a branch called `docs/v2-refactor` which will be the base branch for all documentation changes up to releasing `2.0.0`.

**Comment by troch** [comment]
```diff
# Table of contents

*   [Read Me](../README.md)
*   [Introduction](./introduction/README.md)
    *   [Why Refract?](./introduction/why-refract.md)
    *   [Core Concepts](./introduction/core-concepts.md)
    *   [Thinking In Refract](./introduction/thinking-in-refract.md)
    *   [Alternatives](./introduction/alternatives.md)
*   [Usage](./usage/README.md)
    *   [Getting Started](./usage/getting-started.md)
    *   [Installation](./usage/installation.md)
    *   [Connecting To React](./usage/connecting-to-react.md)
-    *   [Observing React](./usage/observing-react.md)
+    *   [Observing React, Inferno or Preact](./usage/observing-react.md)
-    *   [Observing Inferno and Preact](./usage/observing-inferno.md)
-    *   [Observing Preact](./usage/observing-preact.md)
    *   [Injecting Dependencies](./usage/injecting-dependencies.md)
    *   [Observing Redux](./usage/observing-redux.md)
    *   [Observing Anything](./usage/observing-anything.md)
+    *   [Pushing to props](./usage/pushing-to-props.md)
+    *   [Rendering components](./usage/rendering-components.md)
    *   [Handling Effects](./usage/handling-effects.md)
    *   [Handling Errors](./usage/handling-errors.md)
    *   [Testing](./usage/testing.md)
*   [Recipes](./recipes/README.md)
    *   [Dependency Injection](./recipes/dependency-injection.md)
    *   [Creating An API Dependency](./recipes/creating-an-api-dependency.md)
*   [Examples](../examples/README.md)
    *   [Debounced fetch](../examples/debounced-fetch/README.md)
    *   [Counter](../examples/counter/README.md)
    *   [Field validation](../examples/field-validation/README.md)
    *   [Redux fetch](../examples/redux-fetch/README.md)
    *   [Routing](../examples/routing/README.md)
    *   [Typeahead](../examples/typeahead/README.md)
    *   [Visit time](../examples/visit-time/README.md)
*   [Glossary](./glossary.md)
*   [Feedback](./feedback.md)
```

@jtmcgrath here is what I'm proposing:
- Removing "Observing Inferno / Preact" so it's a bit more compact
- Adding "Pushing to props" and "Rendering components" either before or after "Handling effects".
- Other pages won't change in title or position (but content will need to be updated)

**Comment by jtmcgrath** [comment]
Sounds good! 👌

**Pull request merged**
